---
title: "COVID-19追加接種と死亡率の上昇：非高齢者集団における安全性シグナルの検出"
date: 2025-08-29
format: html
editor: visual
execute: 
  echo: false
  message: false
  warning: false
---

観察期間　2021年2月1日～2024年3月31日

```{r}
# VRS2_results (present analysis results)

# 1. 初期設定
# 自治体固有の設定
municipality_id <- "JP"
municipality_name <- "Japan"
subdir <- paste0("")

# 共通の設定
library(tidyverse)

file_name1 <- function(name) {
  paste0(subdir, municipality_id, "_VRS1a_", name, "_", municipality_name, ".csv")
}
file_name2 <- function(name) {
  paste0(subdir, municipality_id, "_VRS2a_", name, "_", municipality_name, ".csv")
}

readRate1 <- function(name) {
  read_csv(file_name1(name)) |>
    rename(
      rate = incidence_100000_pys,
      rate.lo = incidence_100000_pys_95CI_lower,
      rate.hi = incidence_100000_pys_95CI_upper
    )
}

readRate2 <- function(name) {
  read_csv(file_name2(name)) |>
  mutate(
    rate = rate * 100000,
    rate.lo = rate.lo * 100000,
    rate.hi = rate.hi * 100000
  ) 
}

readSir2 <- function(name) {
  read_csv(file_name2(name))
}

plotRate <- function(df, x, title, xlab) {
  df |>
    ggplot(aes(x = factor({{ x }}), y = rate)) +
    geom_col(width = 0.4, position = "dodge") +
    geom_errorbar(aes(ymin = rate.lo, ymax = rate.hi),
                  position = "dodge",
                  width = 0.1) +
    labs(title = title, x = xlab, y = "全死因死亡率（10万人年当たり）") +
    theme_classic() +
    theme(legend.position = "bottom")
}

plotRate2 <- function(df, x, fill, title, xlab) {
  df |>
    ggplot(aes(x = factor({{ x }}), y = rate,
               fill =factor({{ fill }}))) +
    geom_col(position = "dodge") +
    geom_errorbar(aes(ymin = rate.lo, ymax = rate.hi),
                  position = "dodge") +
    labs(title = title,
         x = xlab,
         y = "全死因死亡率（10万人年当たり）",
         fill = "ワクチン接種回数") +
    theme_classic() +
    theme(legend.position = "bottom")
}

plotSir <- function(df, x,  xlab) {
  df |>
    ggplot(aes(x = {{ x }}, y = sir)) +
    geom_pointrange(aes(ymin = sir.lo, ymax = sir.hi)) +
    geom_hline(yintercept = 1) +
    coord_cartesian(ylim = c(0, 2)) +
    labs(
      title = "標準化死亡比（5,000人年以上）",
      x = xlab,
      y = "標準化死亡比"
    ) +
    theme_classic()
}
```

# 1. 松戸市＋浜松市

## 1.1 全死因死亡率の推定（IncidencePrevalenceによる）

### 分析1　20～49歳　接種回数別［図2］

```{r}
# 分析1
inc_df <- readRate1("1")

inc_df |>
  plotRate(
    x = denominator_target_cohort_name,
    title = "全死因死亡率　20～49歳　接種回数別",
    xlab = "ワクチン接種回数"
  ) +
  scale_x_discrete(
    limits = c("cohort_0", "cohort_1", "cohort_2", "cohort_3", "cohort_4",
               "cohort_5", "cohort_6", "cohort_7"),
    labels = c("0", "1", "2", "3", "4", "5", "6", "7")
  )
```

### 分析2　20～49歳　四半期・接種回数別

```{r}
# 分析2
inc_df <- readRate1("2")

inc_df |>
#  filter(denominator_target_cohort_name != "cohort_1") |>
  plotRate2(
    x = incidence_start_date,
    fill = denominator_target_cohort_name,
    title = "全死因死亡率の推移　20～49歳　接種回数別",
    xlab = "四半期"
  ) +
  scale_fill_discrete(
    limits = c("cohort_0", "cohort_1", "cohort_2", "cohort_3", "cohort_4",
               "cohort_5", "cohort_6", "cohort_7"),
    labels = c("0", "1", "2", "3", "4", "5", "6", "7")
  )
```

### 分析3　50～64歳　接種回数別［図2］

```{r}
# 分析3
inc_df <- readRate1("3")

inc_df |>
  plotRate(
    x = denominator_target_cohort_name,
    title = "全死因死亡率　50～64歳　接種回数別",
    xlab = "ワクチン接種回数"
  ) +
  scale_x_discrete(
    limits = c("cohort_0", "cohort_1", "cohort_2", "cohort_3", "cohort_4",
               "cohort_5", "cohort_6", "cohort_7"),
    labels = c("0", "1", "2", "3", "4", "5", "6", "7")
  )
```

### 分析4　50～64歳　四半期・接種回数別

```{r}
# 分析4
inc_df <- readRate1("4")

inc_df |>
#  filter(denominator_target_cohort_name != "cohort_1") |>
  plotRate2(
    x = incidence_start_date,
    fill = denominator_target_cohort_name,
    title = "全死因死亡率の推移　50～64歳　接種回数別",
    xlab = "四半期"
  ) +
  scale_fill_discrete(
    limits = c("cohort_0", "cohort_1", "cohort_2", "cohort_3", "cohort_4",
               "cohort_5", "cohort_6", "cohort_7"),
    labels = c("0", "1", "2", "3", "4", "5", "6", "7")
  )
```

### 分析5　65～89歳　接種回数別［図2］

```{r}
# 分析5
inc_df <- readRate1("5")

inc_df |>
  plotRate(
    x = denominator_target_cohort_name,
    title = "全死因死亡率　65～89歳　接種回数別",
    xlab = "ワクチン接種回数"
  ) +
  scale_x_discrete(
    limits = c("cohort_0", "cohort_1", "cohort_2", "cohort_3", "cohort_4",
               "cohort_5", "cohort_6", "cohort_7"),
    labels = c("0", "1", "2", "3", "4", "5", "6", "7")
  )
```

### 分析6　65～89歳　四半期・接種回数別

```{r}
# 分析6
inc_df <- readRate1("6")

inc_df |>
#  filter(denominator_target_cohort_name != "cohort_1") |>
  plotRate2(
    x = incidence_start_date,
    fill = denominator_target_cohort_name,
    title = "全死因死亡率の推移　65～89歳　接種回数別",
    xlab = "四半期"
  ) +
  scale_fill_discrete(
    limits = c("cohort_0", "cohort_1", "cohort_2", "cohort_3", "cohort_4",
               "cohort_5", "cohort_6", "cohort_7"),
    labels = c("0", "1", "2", "3", "4", "5", "6", "7")
  )
```

## 1.2 全死因死亡率の推定（popEpiによる）

### 分析1　20～49歳　接種回数別

```{r}
# 分析1
inc_df <- readRate2("rate_1")

inc_df |>
  plotRate(
    x = cohort_definition_id,
    title = "全死因死亡率　20～49歳　接種回数別",
    xlab = "ワクチン接種回数"
  )
```

### 分析2　20～49歳　四半期・接種回数別

```{r}
# 分析2
inc_df <- readRate2("rate_2")

inc_df |>
#  filter(denominator_target_cohort_name != "cohort_1") |>
  plotRate2(
    x = interval,
    fill = cohort_definition_id,
    title = "全死因死亡率の推移　20～49歳　接種回数別",
    xlab = "四半期"
  )
```

### 分析3　50～64歳　接種回数別

```{r}
# 分析3
inc_df <- readRate2("rate_3")

inc_df |>
  plotRate(
    x = cohort_definition_id,
    title = "全死因死亡率　50～64歳　接種回数別",
    xlab = "ワクチン接種回数"
  )
```

### 分析4　60～64歳　四半期・接種回数別

```{r}
# 分析2
inc_df <- readRate2("rate_4")

inc_df |>
#  filter(denominator_target_cohort_name != "cohort_1") |>
  plotRate2(
    x = interval,
    fill = cohort_definition_id,
    title = "全死因死亡率の推移　50～64歳　接種回数別",
    xlab = "四半期"
  )
```

### 分析5　65～89歳　接種回数別

```{r}
# 分析5
inc_df <- readRate2("rate_5")

inc_df |>
  plotRate(
    x = cohort_definition_id,
    title = "全死因死亡率　65～89歳　接種回数別",
    xlab = "ワクチン接種回数"
  )
```

### 分析6　65～89歳　四半期・接種回数別

```{r}
# 分析6
inc_df <- readRate2("rate_6")

inc_df |>
#  filter(denominator_target_cohort_name != "cohort_1") |>
  plotRate2(
    x = interval,
    fill = cohort_definition_id,
    title = "全死因死亡率の推移　65～89歳　接種回数別",
    xlab = "四半期"
  )
```

## 1.3 接種日から死亡日までの間隔［図3］

```{r}
df <- read_csv("JP_VRS1a_duration_Japan.csv") |>
  filter((drug_exposure_id >= 2) & (drug_exposure_id <= 7))

age20_49 <- c(
  "20～24歳", "25～29歳", "30～34歳", "35～39歳", "40～44歳", "45～49歳",
  "2001～2006", "1996～2000", "1991～1995",
  "1986～1990", "1981～1985", "1976～1980"
)
age50_64 <- c(
  "50～54歳", "55～59歳", "60～64歳","1971～1975","1966～1970","1961～1965"
)
age65_89 <- c(
  "65～69歳", "70～74歳", "75～79歳", "80～84歳", "85～89歳",
  "1956～1960", "1951～1955", "1946～1950",
  "1941～1945", "1936～1940"
)
```

### 分析1　20～49歳

```{r}
df |>
  filter(group %in% age20_49) |>
  ggplot(aes(x = duration)) +
  geom_histogram(binwidth = 10) +
  facet_grid(drug_exposure_id ~ .) +
  scale_x_continuous(limits = c(0, 500)) +
  theme_classic()
```

### 分析2　50～64歳

```{r}
df |>
  filter(group %in% age50_64) |>
  ggplot(aes(x = duration)) +
  geom_histogram(binwidth = 10) +
  facet_grid(drug_exposure_id ~ .) +
  scale_x_continuous(limits = c(0, 500)) +
  theme_classic()
```

### 分析3　65～89歳

```{r}
df |>
  filter(group %in% age65_89) |>
  ggplot(aes(x = duration)) +
  geom_histogram(binwidth = 10) +
  facet_grid(drug_exposure_id ~ .) +
  scale_x_continuous(limits = c(0, 500)) +
  theme_classic()
```
